project:
  type: website
  output-dir: docs

website:
  title: "Nathanaël Soulage"
  favicon: favicon.svg
  navbar:
    title: "Nathanaël Soulage"
    search: true
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: Nathanael_Soulage_resume.pdf
  page-footer:
    center: "© 2026 Nathanaël Soulage · Sciences Po"

format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    toc: false
