---
title: "Master's thesis: How to tax housing? Property versus rental taxation"
--- 

This page is dedicated to my Master's thesis, written during the Spring 2025 semester, under the supervision of Prof. Antoine Ferey (Sciences Po). Its title: "How to tax housing? Property versus rental taxation". It has been selected as one of the Best Master's Thesis for the year 2024-2025 ([the selection can be found here]((https://www.sciencespo.fr/ecole-recherche/en/academics/masters/master-economics/best-thesis/))). 

In this essay I look at the differential welfare impact of two types of housing taxes: property and rental income taxation. I first derive a fully theoretical, static, model to characterize the welfare implications of budget-neutral reforms. I then develop a tractable model, that can be numerically simulated, to derive optimal tax rates, under different specifications. Crucially, the optimal tax mix depends on the pass-through of the rental tax burden from the landlords to their tenants, determining the *effective tax incidence*. 
You can find it [here](Mémoire_Soulage_Nathanael.pdf)



