
---
title : "Replication of *Wage stagnation and the decline of standardized pay rates* (Massenkoff & Wilmers, 2023)"
---

For my Labor Economics class (taught by Prof. Pierre Cahuc), I chose to replicate, conducting robustness checks and producing extension, this paper on the drivers of blue-collar wage stagnation in the 1970s-1990s in the US.    

I found that, in line with the authors' findings, the decline of standardized pay rates in the late 1970s and 1980s contributed significantly to wage stagnation, a finding that is robust to the tests that I performed. Moreover, I refined their analysis by showing that the wage decline has primarily (and almost fully) been driven by firms moving away from fully standardized pay structures, with no within-job pay variation, rather than from tenure-based pay. Additionally, I found that bonuses, when used in a firm, primarily benefit white-collar workers, while the effects of piece-rate pay, though apparently significant, are harder to generalize due to limited presence in the data.


- You can find the original paper, its appendix, and its replication package at this [link](https://www.aeaweb.org/articles?id=10.1257/app.20200819).  

- My replication study is available [here](Labor_replication.pdf)

